# Generated by Django 5.1.5 on 2025-01-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='resto_images/')),
            ],
        ),
    ]
