# Generated by Django 5.1.5 on 2025-01-31 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_facility_room_capacity_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('harga_tiket_domestik', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_tiket_mancanegara', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jam_buka', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FotoWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('deskripsi', models.CharField(max_length=255)),
                ('wisata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri_foto', to='homestay.wisata')),
            ],
        ),
    ]
