# Generated by Django 5.1.5 on 2025-01-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0003_wisata_fotowisata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
