# Generated by Django 5.1.5 on 2025-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0006_remove_room_image_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Room Image'),
        ),
    ]
