# Generated by Django 5.1.5 on 2025-02-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0007_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
